### ISSUE TITLE
Scaling gets disabled for others when going into gpose.

### ISSUE THREAD

**Issue by Venichee** [XIV-Tools/CustomizePlus#159] opened 2023-07-17 23:13 UTC
Not sure if it's a Mare issue or an issue with the latest update. But whenever I try to gpose with my friends their scaling gets turned off and theyre back to vanilla settings.

**Comment by StoiaCode** [comment] 2023-07-18 21:00
Can you try again please?

**Comment by lexiconmage** [comment] 2023-07-20 04:03
Running into the same issue. On 1.2.5.2 currently, and it seems like no scaling is applied at all now in gpose, my own included.

**Comment by KattInYourHat** [comment] 2023-07-20 06:06
Same issue. Running 1.2.5.2, Scaling is completely eliminated / reverted upon entering gpose for anyone but myself in the pose.

**Comment by keramjay** [comment] 2023-07-20 16:01
I have the same issue. Going into gpose with someone who uses Customize+ completely removes it for them while this had never been the case

**Comment by misa-92** [comment] 2023-07-21 13:12
one question and that is in gpose when someone takes a picture of me this person in gpose no longer has my customize+ settings so outside I have a nice big tail and narrow spain and in gpose I have a small tail and again a bigger spain what could be there??

**Comment by Virusblue** [comment] 2023-07-25 01:35
Guys im also getting this issue :( i've tried waiting for almost a week but im completely lost on how to fix it. i've tried asking servers seems nobody can solve this for us. (upon gpose i all my friends Customize+ scales are removed however mines remain.) 
PLEASE HELP

**Comment by AmuraHimari** [comment] 2023-07-25 01:36
Having same issue ever sense i updated ver 1.2.5.2 when entering a gpose friends scaling is reverted to default.

**Comment by knucksmchuggins** [comment] 2023-07-26 00:42
Is there a fix for this yet? I wasnt having this issues yesterday now I suddenly am, I make a "living" in game doing Gposes I need mah scaling.

**Comment by StoiaCode** [comment] 2023-07-26 12:07
No Fix yet, you will have to wait.
Don't rely your money flow on free third-party tools made by people in their free time, and especially don't try to shame those people into working faster by acting like its essential.

**Comment by knucksmchuggins** [comment] 2023-07-28 06:08
> No Fix yet, you will have to wait. Don't rely your money flow on free third-party tools made by people in their free time, and especially don't try to shame those people into working faster by acting like its essential.

Whoa, I think my comment was taken way too heavy handed, I am happy to wait as long as it takes, I was just curious if there was a fix yet that I hadn't seen.  I wasn't trying to shame anyone, I was making a light hearted comment about making money from Gposing. Apologies for the miscommunication.

**Comment by danielko160** [comment] 2023-08-04 22:18
Well I found out that for me the issue is - people in my friends list. 
When I tried to gpose with someone in my friend's list - their scaling didn't work.
When I gposed with people not in my friend's list Their scaling was fine.

I tested it with my friends - removing them: scaling works.
Adding them back: doesn't work. 

Don't know if it happens to anyone else, but it happened to my friends as well.
Maybe might help.

**Comment by anthroApologizing** [comment] 2023-08-16 06:24
Still having this issue.  It seems to correlate with the "apply scaling to only self" toggle for me.  I noticed this when I turned it on so my retainer and player portraits would stop adopting my scaling, but as a result I lose scaling while in gpose.  If I leave the toggle off (meaning my retainer in my yard gets my scaling too), it stays in gpose.  Unsure how this interacts with Mare, as I don't use it due to bandwidth issues.

**Comment by StoiaCode** [comment] 2023-08-16 06:27
Idk why people read "Apply scaling to only self" but that literally does not exist

**Comment by anthroApologizing** [comment] 2023-08-16 06:49
probably because people remember the function more than the name itself.
![onlyowned2](https://github.com/XIV-Tools/CustomizePlus/assets/126769975/5d7f2ab0-baf7-4219-a570-6dbe3cfd58d5)
![onlyowned](https://github.com/XIV-Tools/CustomizePlus/assets/126769975/84f90c39-42a5-4885-8f65-c35c1e061f55)
I turn it on to avoid my retainer adopting my personal  scaling (and stop it from applying to party members' portraits), but without fail my scaling on myself does not carry over into gpose.
![onlyothers3](https://github.com/XIV-Tools/CustomizePlus/assets/126769975/384644af-d4ee-44ee-ae22-f7aff7b51d0a)

**Comment by StoiaCode** [comment] 2023-08-16 06:51
Because you dont own your own character in Gpose, funny as it sounds.

**Comment by orenji** [comment] 2023-08-21 07:23
This is happening to me as well as two other friends. When I go into gpose, my custom scaling looks as it should, but those of my friends gets reverted to default. When they gpose, their character looks fine but anyone else gets reverted to default.

**Comment by maramouch** [comment] 2023-10-14 10:24
This is still an issue, I had to change back to vanilla ears because when I get gposes taken by other people (friends or not) my ears look huge and ugly (I have them really heavily edited with customize).

**Comment by StoiaCode** [comment] 2023-10-17 14:06
Then send them your scale.
Or a MCDF for that matter.

**Comment by Presea-diamond** [comment] 2023-10-17 14:13
Well yea that's what I do but it's really inconvenient everytime I go into a club and I have to send the photographer a 300 character code for that >_<

**Comment by orenji** [comment] 2023-10-17 19:13
@StoiaCode Also still an issue for me even after updates. This was not an issue before, therefor sending scales or mcdf's is not a solution to the existing bug. Sending or requesting people's scales and implementing that in every gpose for a group shot is extremely tedious and removes all fun from wanting to take nice shots in the moment. While it is a temporary "solution" posting it here doesn't really help solve the core problem/bug. Posting here is to let the developer know it's still a problem.

**Comment by StoiaCode** [comment] 2023-10-17 19:18
I am the developer you are letting know?  I tell you I know about it.

**Closed** 2023-10-17 20:02 UTC

**Comment by orenji** [comment] 2023-10-18 16:12
@StoiaCode My bad on not realizing you were the developer! If a fix was implemented I look forward to testing later to see if if works on my end! Thank you!
