### ISSUE TITLE
Not interactable duplicate / No Groin IVCS bone with the letter A

### ISSUE THREAD

**Issue by PolarXFusion** [XIV-Tools/CustomizePlus#109] opened 2023-05-02 18:26 UTC
When I edit and or save it as a new scale, It wouldn't let me edit the name for the scale. As well I can't check the duplicate's checkbox.
But if I click the normal it would check both the boxes and editing names would also change both.

Also noticed in the list at Groin that it goes from B to F.

**Comment by StoiaCode** [comment] 2023-05-02 18:30
Cant reproduce either of these, are the scales imported via Anamnesis or created via In Game editor?

Also what bones in Groin. For me it looks lke this: 
![grafik](https://user-images.githubusercontent.com/23234609/235753945-4db79039-a40b-43ec-ac1b-7db9f39df5bc.png)

**Comment by PolarXFusion** [comment] 2023-05-02 18:43
![image](https://user-images.githubusercontent.com/132392614/235756626-1f4bea7a-791e-4f56-ae7c-a26b4fd06951.png)
Sorry didn't noticed A being all the way down.

But the scaling was an Anamnesis pose

**Comment by StoiaCode** [comment] 2023-05-02 18:54
There appears to be a current bug with Ana poses, can you do me a favor and grab this file and upload it here: %APPDATA%\XIVLauncher\pluginConfigs\CustomizePlus.json

**Comment by PolarXFusion** [comment] 2023-05-02 19:22
Did delete the pose before but did manage to reproduce, It was on same character, but one has the pose already while the other is default. So it occurs when importing the same pose on that character though it doesn't do the double check box.
 (sorry if it was zipped couldn't upload a file with a json extension)
[CustomizePlus json file.zip](https://github.com/XIV-Tools/CustomizePlus/files/11377001/CustomizePlus.json.file.zip)

**Comment by StoiaCode** [comment] 2023-06-18 13:10
closing this in favor of #122

**Closed by StoiaCode** 2023-06-18 13:10 UTC
